.TH "Movie Reviews/Helper Classes/Categories Directory Reference" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Movie Reviews/Helper Classes/Categories Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBNSDictionary+Additions\&.h\fP"
.br
.ti -1c
.RI "file \fBNSDictionary+Additions\&.m\fP"
.br
.ti -1c
.RI "file \fBNSError+Additions\&.h\fP"
.br
.ti -1c
.RI "file \fBNSError+Additions\&.m\fP"
.br
.ti -1c
.RI "file \fBUIDevice+Additions\&.h\fP"
.br
.ti -1c
.RI "file \fBUIDevice+Additions\&.m\fP"
.br
.ti -1c
.RI "file \fBUITableView+Additions\&.h\fP"
.br
.ti -1c
.RI "file \fBUITableView+Additions\&.m\fP"
.br
.ti -1c
.RI "file \fBUITableViewCell+Additions\&.h\fP"
.br
.ti -1c
.RI "file \fBUITableViewCell+Additions\&.m\fP"
.br
.ti -1c
.RI "file \fBUIView+Additions\&.h\fP"
.br
.ti -1c
.RI "file \fBUIView+Additions\&.m\fP"
.br
.in -1c
