.TH "Movie Reviews/Helper Classes Directory Reference" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Movie Reviews/Helper Classes Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCategories\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAlertUser\&.h\fP"
.br
.ti -1c
.RI "file \fBAlertUser\&.m\fP"
.br
.in -1c
