.TH "Movie Reviews/Model/API Model Directory Reference" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Movie Reviews/Model/API Model Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDataModels\&.h\fP"
.br
.ti -1c
.RI "file \fBLink\&.h\fP"
.br
.ti -1c
.RI "file \fBLink\&.m\fP"
.br
.ti -1c
.RI "file \fBMovieSearch\&.h\fP"
.br
.ti -1c
.RI "file \fBMovieSearch\&.m\fP"
.br
.ti -1c
.RI "file \fBMultimedia\&.h\fP"
.br
.ti -1c
.RI "file \fBMultimedia\&.m\fP"
.br
.ti -1c
.RI "file \fBNYTLink\&.h\fP"
.br
.ti -1c
.RI "file \fBNYTLink\&.m\fP"
.br
.ti -1c
.RI "file \fBNYTMovieSearch\&.h\fP"
.br
.ti -1c
.RI "file \fBNYTMovieSearch\&.m\fP"
.br
.ti -1c
.RI "file \fBNYTMultimedia\&.h\fP"
.br
.ti -1c
.RI "file \fBNYTMultimedia\&.m\fP"
.br
.ti -1c
.RI "file \fBNYTRelatedUrls\&.h\fP"
.br
.ti -1c
.RI "file \fBNYTRelatedUrls\&.m\fP"
.br
.ti -1c
.RI "file \fBNYTResource\&.h\fP"
.br
.ti -1c
.RI "file \fBNYTResource\&.m\fP"
.br
.ti -1c
.RI "file \fBNYTResults\&.h\fP"
.br
.ti -1c
.RI "file \fBNYTResults\&.m\fP"
.br
.ti -1c
.RI "file \fBRelatedUrls\&.h\fP"
.br
.ti -1c
.RI "file \fBRelatedUrls\&.m\fP"
.br
.ti -1c
.RI "file \fBResource\&.h\fP"
.br
.ti -1c
.RI "file \fBResource\&.m\fP"
.br
.ti -1c
.RI "file \fBResults\&.h\fP"
.br
.ti -1c
.RI "file \fBResults\&.m\fP"
.br
.in -1c
