.TH "Movie Reviews Directory Reference" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Movie Reviews Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBControllers\fP"
.br
.ti -1c
.RI "directory \fBHelper Classes\fP"
.br
.ti -1c
.RI "directory \fBModel\fP"
.br
.ti -1c
.RI "directory \fBSupporting Files\fP"
.br
.ti -1c
.RI "directory \fBViews\fP"
.br
.in -1c
