.TH "Movie Reviews/Controllers Directory Reference" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Movie Reviews/Controllers Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMovieDetailsTableViewController\&.h\fP"
.br
.ti -1c
.RI "file \fBMovieDetailsTableViewController\&.m\fP"
.br
.ti -1c
.RI "file \fBMovieOfflineFavouritesTableViewController\&.h\fP"
.br
.ti -1c
.RI "file \fBMovieOfflineFavouritesTableViewController\&.m\fP"
.br
.ti -1c
.RI "file \fBMovieSearchTableViewController\&.h\fP"
.br
.ti -1c
.RI "file \fBMovieSearchTableViewController\&.m\fP"
.br
.in -1c
