.TH "Movie Reviews/Views/TableViewCells Directory Reference" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Movie Reviews/Views/TableViewCells Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMovieDetailsDescriptionTableViewCell\&.h\fP"
.br
.ti -1c
.RI "file \fBMovieDetailsDescriptionTableViewCell\&.m\fP"
.br
.ti -1c
.RI "file \fBMovieDetailsHeaderTableViewCell\&.h\fP"
.br
.ti -1c
.RI "file \fBMovieDetailsHeaderTableViewCell\&.m\fP"
.br
.ti -1c
.RI "file \fBMovieDetailsReviewTableViewCell\&.h\fP"
.br
.ti -1c
.RI "file \fBMovieDetailsReviewTableViewCell\&.m\fP"
.br
.ti -1c
.RI "file \fBMovieListTableViewCell\&.h\fP"
.br
.ti -1c
.RI "file \fBMovieListTableViewCell\&.m\fP"
.br
.in -1c
