.TH "Movie Reviews/Model/API Interaction Directory Reference" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Movie Reviews/Model/API Interaction Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBInteractWithAPI\&.h\fP"
.br
.ti -1c
.RI "file \fBInteractWithAPI\&.m\fP"
.br
.ti -1c
.RI "file \fBInteractWithModel\&.h\fP"
.br
.ti -1c
.RI "file \fBInteractWithModel\&.m\fP"
.br
.ti -1c
.RI "file \fBUITableViewCell+APICell\&.h\fP"
.br
.ti -1c
.RI "file \fBUITableViewCell+APICell\&.m\fP"
.br
.in -1c
