.TH "AlertUser" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AlertUser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <AlertUser\&.h>\fP
.PP
Inherits NSObject\&.
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(void) + \fBdisableUserInteractionWithView:displayActivityIndicator:\fP"
.br
.ti -1c
.RI "(void) + \fBenableUserInteractionWithView:hideActivityIndicator:\fP"
.br
.ti -1c
.RI "(void) + \fBsetUserInteractionOfView:to:\fP"
.br
.ti -1c
.RI "(BOOL) + \fBhideActivityIndicatorFromView:\fP"
.br
.ti -1c
.RI "(void) + \fBshowActivityIndicatorInCenterOfView:\fP"
.br
.ti -1c
.RI "(void) + \fBshowActivityIndicatorInView:withCenter:\fP"
.br
.ti -1c
.RI "(MBProgressHUD *) + \fBshowInitialProgressHUDAddedTo:withMessage:animated:\fP"
.br
.ti -1c
.RI "(MBProgressHUD *) + \fBmodifyProgressHUDInView:withMessage:\fP"
.br
.ti -1c
.RI "(void) + \fBshowFinalProgressHUDAddedTo:withMessage:isSuccessFull:dismissAfterDelay:animated:\fP"
.br
.ti -1c
.RI "(BOOL) + \fBhideProgressHUDForView:animated:\fP"
.br
.ti -1c
.RI "(void) + \fBshowError:customTitle:\fP"
.br
.ti -1c
.RI "(void) + \fBshowSuccess:customTitleMessage:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Root class that is responsible for all user interaction 
.PP
Definition at line 16 of file AlertUser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Movie Reviews from the source code\&.
