.TH "AppDelegate()" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppDelegate() \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 13 of file AppDelegate\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Movie Reviews from the source code\&.
