.TH "MovieSearchTableViewController" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MovieSearchTableViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MovieSearchTableViewController\&.h>\fP
.PP
Inherits UITableViewController\&.
.SH "Detailed Description"
.PP 
The Controller with which users can search the NYT Movie Reviews API and view the results\&. It uses the deprecated searchDisplayController to maintain compatibility with iOS 7\&. Search occurs 0\&.4 seconds after each letter is typed, if another letter is typed in those 0\&.4 seconds then the previous search request gets cancelled\&. This way the search doesnt send any requests we dont want it to\&. 
.PP
Definition at line 13 of file MovieSearchTableViewController\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Movie Reviews from the source code\&.
