.TH "MovieDetailsTableViewController" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MovieDetailsTableViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MovieDetailsTableViewController\&.h>\fP
.PP
Inherits UITableViewController\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBNYTResults\fP * \fBonlineSelection\fP"
.br
.ti -1c
.RI "\fBResults\fP * \fBofflineSelection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The controller that will display all of the information for the selected movie 
.PP
Definition at line 14 of file MovieDetailsTableViewController\&.h\&.
.SH "Property Documentation"
.PP 
.SS "\- (\fBResults\fP*) offlineSelection\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
The selected movie from the favourites 
.PP
Definition at line 22 of file MovieDetailsTableViewController\&.h\&.
.SS "\- (\fBNYTResults\fP*) onlineSelection\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
The selected movie from the online search results 
.PP
Definition at line 18 of file MovieDetailsTableViewController\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Movie Reviews from the source code\&.
