.TH "MovieOfflineFavouritesTableViewController" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MovieOfflineFavouritesTableViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MovieOfflineFavouritesTableViewController\&.h>\fP
.PP
Inherits UITableViewController\&.
.SH "Detailed Description"
.PP 
The Controller responsible for displaying the user's favourites, it used an NSFetchedResults controller to query core data 
.PP
Definition at line 13 of file MovieOfflineFavouritesTableViewController\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Movie Reviews from the source code\&.
