.TH "MovieOfflineFavouritesTableViewController()" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MovieOfflineFavouritesTableViewController() \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits <DZNEmptyDataSetSource>, <DZNEmptyDataSetDelegate>, and <NSFetchedResultsControllerDelegate>\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSFetchedResultsController * \fBfetchedResultsController\fP"
.br
.ti -1c
.RI "UITableViewCell * \fBheightCell\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file MovieOfflineFavouritesTableViewController\&.m\&.
.SH "Property Documentation"
.PP 
.SS "\- (NSFetchedResultsController*) fetchedResultsController\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
Interfaces with core data to return the user's favourites 
.PP
Definition at line 30 of file MovieOfflineFavouritesTableViewController\&.m\&.
.SS "\- (UITableViewCell*) heightCell\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"
Is used to automatically calculate the cell height on iOS7 
.PP
Definition at line 36 of file MovieOfflineFavouritesTableViewController\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Movie Reviews from the source code\&.
