.TH "NYTLink()" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NYTLink() \- 
.SH SYNOPSIS
.br
.PP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(id) \- \fBobjectOrNilForKey:fromDictionary:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file NYTLink\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Movie Reviews from the source code\&.
