.TH "NYTMovieSearch" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NYTMovieSearch \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <NYTMovieSearch\&.h>\fP
.PP
Inherits NSObject, <NSCoding>, and <NSCopying>\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(instancetype) \- \fBinitWithDictionary:\fP"
.br
.ti -1c
.RI "(NSDictionary *) \- \fBdictionaryRepresentation\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(instancetype) + \fBmodelObjectWithDictionary:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBstatus\fP"
.br
.ti -1c
.RI "NSArray * \fBresults\fP"
.br
.ti -1c
.RI "NSString * \fBcopyright\fP"
.br
.ti -1c
.RI "NSNumber * \fBnumResults\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A Model object representing the search results parsed from the JSON response of the NYT Movie reviews API 
.PP
Definition at line 12 of file NYTMovieSearch\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Movie Reviews from the source code\&.
