.TH "NYTResults" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NYTResults \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <NYTResults\&.h>\fP
.PP
Inherits NSObject, <NSCoding>, and <NSCopying>\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(instancetype) \- \fBinitWithDictionary:\fP"
.br
.ti -1c
.RI "(NSDictionary *) \- \fBdictionaryRepresentation\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(instancetype) + \fBmodelObjectWithDictionary:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBcapsuleReview\fP"
.br
.ti -1c
.RI "NSString * \fBdateUpdated\fP"
.br
.ti -1c
.RI "NSString * \fBsummaryShort\fP"
.br
.ti -1c
.RI "NSString * \fBheadline\fP"
.br
.ti -1c
.RI "NSString * \fBthousandBest\fP"
.br
.ti -1c
.RI "NSString * \fBbyline\fP"
.br
.ti -1c
.RI "NSString * \fBdvdReleaseDate\fP"
.br
.ti -1c
.RI "\fBNYTLink\fP * \fBlink\fP"
.br
.ti -1c
.RI "NSString * \fBmpaaRating\fP"
.br
.ti -1c
.RI "\fBNYTMultimedia\fP * \fBmultimedia\fP"
.br
.ti -1c
.RI "NSString * \fBpublicationDate\fP"
.br
.ti -1c
.RI "NSString * \fBopeningDate\fP"
.br
.ti -1c
.RI "NSString * \fBdisplayTitle\fP"
.br
.ti -1c
.RI "NSArray * \fBrelatedUrls\fP"
.br
.ti -1c
.RI "NSString * \fBsortName\fP"
.br
.ti -1c
.RI "NSString * \fBseoName\fP"
.br
.ti -1c
.RI "NSNumber * \fBcriticsPick\fP"
.br
.ti -1c
.RI "NSNumber * \fBnytMovieId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A Model object representing a movie from parsed from the JSON response of the NYT Movie reviews API 
.PP
Definition at line 14 of file NYTResults\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Movie Reviews from the source code\&.
