.TH "Resource" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Resource \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits NSManagedObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBsrc\fP"
.br
.ti -1c
.RI "NSNumber * \fBwidth\fP"
.br
.ti -1c
.RI "NSString * \fBtype\fP"
.br
.ti -1c
.RI "NSNumber * \fBheight\fP"
.br
.ti -1c
.RI "\fBMultimedia\fP * \fBmultimedia\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file Resource\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Movie Reviews from the source code\&.
