.TH "UIDevice(Additions)" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIDevice(Additions) \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <UIDevice+Additions\&.h>\fP
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(BOOL) + \fBisiPad\fP"
.br
.ti -1c
.RI "(NSString *) + \fBdeviceModel\fP"
.br
.ti -1c
.RI "(NSInteger) + \fBmajorSystemVersion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper category to get different info about the device\&. 
.PP
Definition at line 15 of file UIDevice+Additions\&.h\&.
.SH "Method Documentation"
.PP 
.SS "+ (NSString *) deviceModel "
Returns the current device model\&. 
.PP
Definition at line 33 of file UIDevice+Additions\&.m\&.
.SS "+ (BOOL) isiPad "
Tells whether the current device is an iPad\&. 
.PP
Definition at line 25 of file UIDevice+Additions\&.m\&.
.SS "+ (NSInteger) majorSystemVersion "
Returns the major version of the operating system\&. 
.PP
Definition at line 84 of file UIDevice+Additions\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Movie Reviews from the source code\&.
