.TH "UITableView(Additions)" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UITableView(Additions) \- 
.SH SYNOPSIS
.br
.PP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(void) \- \fBshowTableMessage:\fP"
.br
.ti -1c
.RI "(void) \- \fBshowTableMessage:atPosition:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file UITableView+Additions\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Movie Reviews from the source code\&.
