.TH "UIView(Additions)" 3 "Tue Aug 11 2015" "Movie Reviews" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIView(Additions) \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <UIView+Additions\&.h>\fP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(void) \- \fBstartViewRotation\fP"
.br
.ti -1c
.RI "(void) \- \fBstopViewRotation\fP"
.br
.ti -1c
.RI "(void) \- \fBsetUserInteractionTo:\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBhideActivityIndicator\fP"
.br
.ti -1c
.RI "(void) \- \fBshowActivityIndicatorInCenter\fP"
.br
.ti -1c
.RI "(void) \- \fBshowActivityIndicatorWithCenter:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper category on UIView that deals with user interaction - displaying activity indicator, rotating a view(like an update button) etc 
.PP
Definition at line 15 of file UIView+Additions\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Movie Reviews from the source code\&.
